// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYiUvqUbVHzqop_wmTbEnhZ3VhLySG2vc',
    appId: '1:616858632047:web:0083b1cc06f939602df29a',
    messagingSenderId: '616858632047',
    projectId: 'hackaton-78e84',
    authDomain: 'hackaton-78e84.firebaseapp.com',
    storageBucket: 'hackaton-78e84.appspot.com',
    measurementId: 'G-RPQC062Q4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAfYltOjZfmOBJgTPIINLc7otapFZ949I',
    appId: '1:616858632047:android:aea7f9b5fafcab8e2df29a',
    messagingSenderId: '616858632047',
    projectId: 'hackaton-78e84',
    storageBucket: 'hackaton-78e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvaqiuAgzLhuavpCdlkHQCKOGr5re-PI',
    appId: '1:616858632047:ios:103674c1ae387db82df29a',
    messagingSenderId: '616858632047',
    projectId: 'hackaton-78e84',
    storageBucket: 'hackaton-78e84.appspot.com',
    iosClientId: '616858632047-j916fnebtsqs7kprg7c033ugkesr5537.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
